### PR TITLE
Added CMake For Unix system using FindAPACHE FindAPR in cmake

### PR DESCRIPTION
**Pull request by toniotelli**

### CODE REVIEW

**Comment by jchampio** [comment]
Thanks for this! I'll review and comment on the commit itself. Two initial questions:
1. Where did the FindAPR and FindAPACHE CMake modules come from? BlackDuck found a huge number of similar files and I don't know where they originated.
2. Would you mind reformatting your commit message to a roughly 50 character summary (and if you add a body, wrap it to 72)? That way the git-log stays clean. A general example commit can be found [here](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html) and there are probably tons of other places with more.

It's probably about time for me to write a `CONTRIBUTING` file to help with this...

**Comment by jchampio** [comment]
Hmm. GitHub doesn't put the context with the comments in this conversation, which is unfortunate. Sorry to spam the conversation with one comment per issue instead of having just one overall review; hopefully GitHub doesn't send you an email for each...

Thanks again for your work on this! Let me know what you think about my comments; I'm definitely a CMake beginner. I also added a `CONTRIBUTING.md` with some starting guidelines, so if you have any thoughts on that, I'd be happy to hear them.

**Comment by toniotelli** [comment]
1. I did, indeed find FindAPACHE and FindAPR from somewhere on github. I am not sure which one (might be geomapserver but that's a long shot). 
   One can use from apache: [FindAPR.cmake](https://svn.apache.org/repos/asf/celix/trunk/cmake/FindAPR.cmake)
   Or those ones from github: [OpenSource/mod_dup](https://github.com/Orange-OpenSource/mod_dup/tree/master/cmake/modules)
2. I have worked a bit more on the CMakeUnix.cmake that I could push with a longer description If you wish and I will fixed all the comments

**Comment by toniotelli** [comment]
The last commit should be the good one now (More information in the commit body).

Thanks for your review and feedback.

**Comment by jchampio** [comment]
Great, thanks for that (especially the style changes)!

Since the authorship of the CMake find modules isn't quite clear, I think what I'll do is learn how to write them and reimplement them with the bare minimum needed for our build. It'll be a good way to add APR-2 support as well (since it looks like the current find modules don't support it).

At this point, I plan to squash these four commits into a topic branch, then
1. split the example modules `GLOB` apart
2. switch to an `apxs`-based installation/activation routine (if possible)
3. reimplement the find modules with what we need
4. refactor common code from the Win32 and Unix sides back up into `CMakeLists.txt`.

Once that's done, we can make sure my changes still work for you, and then merge the topic. Thanks again for your work on this!

**Comment by jchampio** [comment]
@toniotelli: The `dev/cmake-unix` branch has my reimplementations of the find modules (among other things, it now supports APR-2 as well as 1.x), and it now uses `apxs` for installation. Can you give it a try and let me know if it works for you?

**Comment by jchampio** [comment]
@toniotelli : any thoughts?

**Comment by jchampio** [comment]
@toniotelli: I'm planning to merge `dev/cmake-unix` into trunk, since it's currently working for me, and I don't believe I've removed any of your functionality with my refactoring. That said, I don't currently have a Mac to test on, so if you find any problems, feel free to open an issue. And thanks again!

**Pull request closed without merging**
